#!/bin/bash

printf '\nDeno REST API Integration Tests\n'
curl -X GET 'localhost:8000/api/v1/accounts'
printf ''
curl -X GET 'localhost:8000/api/v1/accounts/1234'
printf ''
curl -X GET 'localhost:8000/api/v1/products'
printf ''
curl -X GET 'localhost:8000/api/v1/products/112233/regions/Tuscanny'
printf ''
curl -X GET 'localhost:8000/api/v1/health'
printf ''
curl -X GET 'localhost:8000/api/v1/health/info'
printf ''