#!/bin/bash

printf '\nDeno REST API Integration Tests\n\n'
curl -X GET 'localhost:8000/api/v1/accounts'
printf '\n'
curl -X GET 'localhost:8000/api/v1/accounts/1234'
printf '\n'
curl -X GET 'localhost:8000/api/v1/products'
printf '\n'
curl -X GET 'localhost:8000/api/v1/products/112233/regions/Tuscanny'
printf '\n'
curl -X GET 'localhost:8000/api/v1/health'
printf '\n'
curl -X GET 'localhost:8000/api/v1/health/info'
printf '\n'